{% set name = "sphinxcontrib-doxylink" %}
{% set version = "1.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 62c75c150ea62521518e995cafbaa5e763ed8067d15e6fb0a582f6d6aaffe4ab

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - pyparsing >=3.0.8,<4.0.0
    - python-dateutil >=2.8.2,<3.0.0
    - python >={{ python_min }},<4.0
    - sphinx >=1.6

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - sphinxcontrib.doxylink
  commands:
    # check requirements
    - python -m pip check

about:
  home: http://sphinxcontrib-doxylink.readthedocs.io
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx extension for linking to Doxygen documentation.
  doc_url: http://sphinxcontrib-doxylink.readthedocs.io
  dev_url: https://github.com/sphinx-contrib/doxylink

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - duncanmmacleod
    - erykoff
