{% set name = "sphinxcontrib-doxylink" %}
{% set version = "1.12.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 167f2a35e840e37d38427d9ff22409eb1b0f1f17c6189155e083364c4e54b81a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - pyparsing >=3.0.8,<4.0.0
    - python-dateutil >=2.8.2,<3.0.0
    - python >={{ python_min }},<4.0
    - sphinx >=1.6

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - sphinxcontrib.doxylink
  commands:
    # check requirements
    - python -m pip check

about:
  home: http://sphinxcontrib-doxylink.readthedocs.io
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx extension for linking to Doxygen documentation.
  doc_url: http://sphinxcontrib-doxylink.readthedocs.io
  dev_url: https://github.com/sphinx-contrib/doxylink

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - duncanmmacleod
    - erykoff
